// Regenerates src/lib/suppliers.ts from the CNMC supplier register
// (https://sede.cnmc.gob.es/listado/censo/2), exported as CSV to data/cnmc-suppliers.csv.
import { readFileSync, writeFileSync } from "node:fs";

const small = new Set(["de", "del", "la", "las", "el", "los", "y", "e", "en"]);
// Legal forms compared without dots, spaces or case: "S.L.U." and "S L U" both read "slu".
const legalForms =
  /^(sa|sau|sl|slu|sll|sc|scl|scv|scoopv|scoopm|scoopmad|scoopand|scoop|scoopval|coop|coopv|coopvl|coopval|sdadcoopvalenciana|unipersonal|sociedadanonima|sca|sociedadlimitada|sociedadlimitadaunipersonal|sociedadcooperativa|sociedadcooperativavalenciana|sl unipersonal)$/;
const squash = (s: string) => s.toLowerCase().replace(/[.\s,-]/g, "");

function cleanName(name: string) {
  let words = name
    .replace(/[(-]\s*extinguida\s*[)-]?/i, "")
    .replace(/,/g, ", ")
    .trim()
    .split(/\s+/);
  // Drop trailing words while the last one, two or three of them form a legal form.
  for (let changed = true; changed && words.length > 1;) {
    changed = false;
    for (const size of [3, 2, 1]) {
      if (
        words.length > size &&
        legalForms.test(squash(words.slice(-size).join(" ")))
      ) {
        words = words.slice(0, -size);
        changed = true;
        break;
      }
    }
  }
  return words
    .join(" ")
    .replace(/[,.\s-]+$/, "")
    .toLowerCase()
    .split(" ")
    .map((word, index) =>
      index > 0 && small.has(word)
        ? word
        : word.replace(/^(\p{L})/u, (letter) => letter.toUpperCase()),
    )
    .join(" ");
}

const rows = readFileSync("data/cnmc-suppliers.csv", "utf8")
  .trim()
  .split(/\r?\n/)
  .slice(1)
  .map((line) => [...line.matchAll(/"((?:[^"]|"")*)"/g)].map((m) => m[1]));
const names = Object.fromEntries(
  rows
    .filter(([code, name]) => /^R2-\d+$/.test(code) && name)
    .map(([code, name]) => [code, cleanName(name)]),
);
writeFileSync(
  "src/lib/suppliers.ts",
  `// Generated by scripts/generate-suppliers.ts from the CNMC supplier register. Do not edit.\n` +
    `// Includes deregistered suppliers, because older invoices can name them.\n` +
    `export const supplierNames: Record<string, string> = ${JSON.stringify(names, null, 2)};\n`,
);
console.log(`${Object.keys(names).length} suppliers`);
